import { CommanderDamage } from './commanderDamage.model';

export class Player {

  /**
   * This player's unique id. If player is logged in through Google or some other means,
   * this id will be generated by that service, otherwise, the login id is a string of
   * numbers randomly generated.
   *
   * @private
   * @type {string}
   * @memberof Player
   */
  private _id: string;
  public get id(): string { return this._id; }
  public set id(value: string) { this._id = value; }

  /**
   * The player's username.
   *
   * @private
   * @type {string}
   * @memberof Player
   */
  private _name: string;
  public get name(): string { return this._name; }
  public set name(value: string) { this._name = value; }

  /**
   * The player's current life total.
   *
   * @private
   * @type {number}
   * @memberof Player
   */
  private _lifeTotal: number;
  public get lifeTotal(): number { return this._lifeTotal; }
  public set lifeTotal(value: number) { this._lifeTotal = value; }

  /**
   * Commander Attack is the boolean dictating whether this player is currently
   * attacking with his/her commander and, therefore, this damage should be logged
   * as commander damage.
   *
   * @private
   * @type {boolean}
   * @memberof Player
   */
  private _commanderAttack: boolean;
  public get commanderAttack(): boolean { return this._commanderAttack; }
  public set commanderAttack(value: boolean) { this._commanderAttack = value; }

  /**
   * An array of commander damage dealt to this player by other players.
   *
   * @private
   * @type {*}
   * @memberof Player
   */
  private _commanderDamage: any;
  public get commanderDamage(): any { return this._commanderDamage; }
  public set commanderDamage(value: any) { this._commanderDamage = value; }

  constructor (name: string = 'unknown', lifeTotal: number = 40, id?: string) {
    this.name = name;
    this.lifeTotal = lifeTotal;
    this.id = id || (Date.now() + Math.floor(Math.random() * 1000000) + 1).toString();
    this.commanderAttack = false;
    this.commanderDamage = [];
  }
}
