// steps to get list of sets from MTG.io
// 1. do an allSets call on the mtgApiService
// 2. use this function:
  // public sets () {
  //   this.api.getAllSets().subscribe(sets => {
  //     this.array = [];
  //     const allSets = sets.sets;
  //     allSets.forEach(set => {
  //       this.array.push(`{ code: "${set.code}", name: "${set.name}" },`);
  //     });
  //     console.log(this.array);
  //   });
  // }
// 3. print it out to the screen using: <div *ngFor="let set of array">{{ set }}</div>

export const Sets = [
  { code: 'LEA', name: 'Limited Edition Alpha' },
  { code: 'LEB', name: 'Limited Edition Beta' },
  { code: 'ARN', name: 'Arabian Nights' },
  { code: '2ED', name: 'Unlimited Edition' },
  { code: 'CED', name: 'Collector\'s Edition' },
  { code: 'CEI', name: 'International Collector\'s Edition' },
  { code: 'pDRC', name: 'Dragon Con' },
  { code: 'ATQ', name: 'Antiquities' },
  { code: '3ED', name: 'Revised Edition' },
  { code: 'LEG', name: 'Legends' },
  { code: 'DRK', name: 'The Dark' },
  { code: 'FEM', name: 'Fallen Empires' },
  { code: 'pMEI', name: 'Media Inserts' },
  { code: 'pLGM', name: 'Legend Membership' },
  { code: '4ED', name: 'Fourth Edition' },
  { code: 'ICE', name: 'Ice Age' },
  { code: 'CHR', name: 'Chronicles' },
  { code: 'HML', name: 'Homelands' },
  { code: 'ALL', name: 'Alliances' },
  { code: 'RQS', name: 'Rivals Quick Start Set' },
  { code: 'pARL', name: 'Arena League' },
  { code: 'pCEL', name: 'Celebration' },
  { code: 'MIR', name: 'Mirage' },
  { code: 'MGB', name: 'Multiverse Gift Box' },
  { code: 'ITP', name: 'Introductory Two-Player Set' },
  { code: 'VIS', name: 'Visions' },
  { code: '5ED', name: 'Fifth Edition' },
  { code: 'pPOD', name: 'Portal Demo Game' },
  { code: 'POR', name: 'Portal' },
  { code: 'VAN', name: 'Vanguard' },
  { code: 'WTH', name: 'Weatherlight' },
  { code: 'pPRE', name: 'Prerelease Events' },
  { code: 'TMP', name: 'Tempest' },
  { code: 'STH', name: 'Stronghold' },
  { code: 'PO2', name: 'Portal Second Age' },
  { code: 'pJGP', name: 'Judge Gift Program' },
  { code: 'EXO', name: 'Exodus' },
  { code: 'UGL', name: 'Unglued' },
  { code: 'pALP', name: 'Asia Pacific Land Program' },
  { code: 'USG', name: 'Urza\'s Saga' },
  { code: 'ATH', name: 'Anthologies' },
  { code: 'ULG', name: 'Urza\'s Legacy' },
  { code: '6ED', name: 'Classic Sixth Edition' },
  { code: 'PTK', name: 'Portal Three Kingdoms' },
  { code: 'UDS', name: 'Urza\'s Destiny' },
  { code: 'S99', name: 'Starter 1999' },
  { code: 'pGRU', name: 'Guru' },
  { code: 'pWOR', name: 'Worlds' },
  { code: 'pWOS', name: 'Wizards of the Coast Online Store' },
  { code: 'MMQ', name: 'Mercadian Masques' },
  { code: 'BRB', name: 'Battle Royale Box Set' },
  { code: 'pSUS', name: 'Super Series' },
  { code: 'pFNM', name: 'Friday Night Magic' },
  { code: 'pELP', name: 'European Land Program' },
  { code: 'NMS', name: 'Nemesis' },
  { code: 'S00', name: 'Starter 2000' },
  { code: 'PCY', name: 'Prophecy' },
  { code: 'BTD', name: 'Beatdown Box Set' },
  { code: 'INV', name: 'Invasion' },
  { code: 'PLS', name: 'Planeshift' },
  { code: '7ED', name: 'Seventh Edition' },
  { code: 'pMPR', name: 'Magic Player Rewards' },
  { code: 'APC', name: 'Apocalypse' },
  { code: 'ODY', name: 'Odyssey' },
  { code: 'DKM', name: 'Deckmasters' },
  { code: 'TOR', name: 'Torment' },
  { code: 'JUD', name: 'Judgment' },
  { code: 'ONS', name: 'Onslaught' },
  { code: 'LGN', name: 'Legions' },
  { code: 'SCG', name: 'Scourge' },
  { code: 'pREL', name: 'Release Events' },
  { code: '8ED', name: 'Eighth Edition' },
  { code: 'MRD', name: 'Mirrodin' },
  { code: 'DST', name: 'Darksteel' },
  { code: '5DN', name: 'Fifth Dawn' },
  { code: 'CHK', name: 'Champions of Kamigawa' },
  { code: 'UNH', name: 'Unhinged' },
  { code: 'BOK', name: 'Betrayers of Kamigawa' },
  { code: 'SOK', name: 'Saviors of Kamigawa' },
  { code: '9ED', name: 'Ninth Edition' },
  { code: 'RAV', name: 'Ravnica: City of Guilds' },
  { code: 'p2HG', name: 'Two-Headed Giant Tournament' },
  { code: 'pGTW', name: 'Gateway' },
  { code: 'GPT', name: 'Guildpact' },
  { code: 'pCMP', name: 'Champs and States' },
  { code: 'DIS', name: 'Dissension' },
  { code: 'CSP', name: 'Coldsnap' },
  { code: 'CST', name: 'Coldsnap Theme Decks' },
  { code: 'V11', name: 'From the Vault: Legends' },
  { code: 'TSP', name: 'Time Spiral' },
  { code: 'TSB', name: 'Time Spiral ' },
  { code: 'pHHO', name: 'Happy Holidays' },
  { code: 'PLC', name: 'Planar Chaos' },
  { code: 'pPRO', name: 'Pro Tour' },
  { code: 'pGPX', name: 'Grand Prix' },
  { code: 'FUT', name: 'Future Sight' },
  { code: '10E', name: 'Tenth Edition' },
  { code: 'pMGD', name: 'Magic Game Day' },
  { code: 'MED', name: 'Masters Edition' },
  { code: 'LRW', name: 'Lorwyn' },
  { code: 'EVG', name: 'Duel Decks: Elves vs. Goblins' },
  { code: 'pLPA', name: 'Launch Parties' },
  { code: 'MOR', name: 'Morningtide' },
  { code: 'p15A', name: '15th Anniversary' },
  { code: 'DDH', name: 'Duel Decks: Ajani vs. Nicol Bolas' },
  { code: 'SHM', name: 'Shadowmoor' },
  { code: 'pSUM', name: 'Summer of Magic' },
  { code: 'EVE', name: 'Eventide' },
  { code: 'DRB', name: 'From the Vault: Dragons' },
  { code: 'ME2', name: 'Masters Edition II' },
  { code: 'pWPN', name: 'Wizards Play Network' },
  { code: 'ALA', name: 'Shards of Alara' },
  { code: 'DD2', name: 'Duel Decks: Jace vs. Chandra' },
  { code: 'CON', name: 'Conflux' },
  { code: 'DDC', name: 'Duel Decks: Divine vs. Demonic' },
  { code: 'ARB', name: 'Alara Reborn' },
  { code: 'M10', name: 'Magic 2010' },
  { code: 'V09', name: 'From the Vault: Exiled' },
  { code: 'HOP', name: 'Planechase' },
  { code: 'ME3', name: 'Masters Edition III' },
  { code: 'ZEN', name: 'Zendikar' },
  { code: 'DDD', name: 'Duel Decks: Garruk vs. Liliana' },
  { code: 'H09', name: 'Premium Deck Series: Slivers' },
  { code: 'WWK', name: 'Worldwake' },
  { code: 'DDE', name: 'Duel Decks: Phyrexia vs. the Coalition' },
  { code: 'ROE', name: 'Rise of the Eldrazi' },
  { code: 'DPA', name: 'Duels of the Planeswalkers' },
  { code: 'ARC', name: 'Archenemy' },
  { code: 'M11', name: 'Magic 2011' },
  { code: 'V10', name: 'From the Vault: Relics' },
  { code: 'DDF', name: 'Duel Decks: Elspeth vs. Tezzeret' },
  { code: 'SOM', name: 'Scars of Mirrodin' },
  { code: 'PD2', name: 'Premium Deck Series: Fire and Lightning' },
  { code: 'ME4', name: 'Masters Edition IV' },
  { code: 'MBS', name: 'Mirrodin Besieged' },
  { code: 'DDG', name: 'Duel Decks: Knights vs. Dragons' },
  { code: 'NPH', name: 'New Phyrexia' },
  { code: 'CMD', name: 'Magic: The Gathering-Commander' },
  { code: 'M12', name: 'Magic 2012' },
  { code: 'ISD', name: 'Innistrad' },
  { code: 'PD3', name: 'Premium Deck Series: Graveborn' },
  { code: 'DKA', name: 'Dark Ascension' },
  { code: 'DDI', name: 'Duel Decks: Venser vs. Koth' },
  { code: 'AVR', name: 'Avacyn Restored' },
  { code: 'PC2', name: 'Planechase 2012 Edition' },
  { code: 'M13', name: 'Magic 2013' },
  { code: 'V12', name: 'From the Vault: Realms' },
  { code: 'DDJ', name: 'Duel Decks: Izzet vs. Golgari' },
  { code: 'RTR', name: 'Return to Ravnica' },
  { code: 'CM1', name: 'Commander\'s Arsenal' },
  { code: 'GTC', name: 'Gatecrash' },
  { code: 'DDK', name: 'Duel Decks: Sorin vs. Tibalt' },
  { code: 'pWCQ', name: 'World Magic Cup Qualifiers' },
  { code: 'DGM', name: 'Dragon\'s Maze' },
  { code: 'MMA', name: 'Modern Masters' },
  { code: 'M14', name: 'Magic 2014 Core Set' },
  { code: 'V13', name: 'From the Vault: Twenty' },
  { code: 'DDL', name: 'Duel Decks: Heroes vs. Monsters' },
  { code: 'THS', name: 'Theros' },
  { code: 'C13', name: 'Commander 2013 Edition' },
  { code: 'BNG', name: 'Born of the Gods' },
  { code: 'DDM', name: 'Duel Decks: Jace vs. Vraska' },
  { code: 'JOU', name: 'Journey into Nyx' },
  { code: 'MD1', name: 'Modern Event Deck 2014' },
  { code: 'CNS', name: 'Magic: The Gathering—Conspiracy' },
  { code: 'VMA', name: 'Vintage Masters' },
  { code: 'M15', name: 'Magic 2015 Core Set' },
  { code: 'CPK', name: 'Clash Pack' },
  { code: 'V14', name: 'From the Vault: Annihilation (2014)' },
  { code: 'DDN', name: 'Duel Decks: Speed vs. Cunning' },
  { code: 'C15', name: 'Commander 2015' },
  { code: 'KTK', name: 'Khans of Tarkir' },
  { code: 'C14', name: 'Commander 2014' },
  { code: 'DD3_DVD', name: 'Duel Decks Anthology, Divine vs. Demonic' },
  { code: 'DD3_EVG', name: 'Duel Decks Anthology, Elves vs. Goblins' },
  { code: 'DD3_GVL', name: 'Duel Decks Anthology, Garruk vs. Liliana' },
  { code: 'DD3_JVC', name: 'Duel Decks Anthology, Jace vs. Chandra' },
  { code: 'FRF_UGIN', name: 'Ugin\'s Fate promos' },
  { code: 'FRF', name: 'Fate Reforged' },
  { code: 'DDO', name: 'Duel Decks: Elspeth vs. Kiora' },
  { code: 'DTK', name: 'Dragons of Tarkir' },
  { code: 'TPR', name: 'Tempest Remastered' },
  { code: 'MM2', name: 'Modern Masters 2015 Edition' },
  { code: 'ORI', name: 'Magic Origins' },
  { code: 'V15', name: 'From the Vault: Angels' },
  { code: 'DDP', name: 'Duel Decks: Zendikar vs. Eldrazi' },
  { code: 'BFZ', name: 'Battle for Zendikar' },
  { code: 'EXP', name: 'Zendikar Expeditions' },
  { code: 'OGW', name: 'Oath of the Gatewatch' },
  { code: 'DDQ', name: 'Duel Decks: Blessed vs. Cursed' },
  { code: 'W16', name: 'Welcome Deck 2016' },
  { code: 'SOI', name: 'Shadows over Innistrad' },
  { code: 'EMA', name: 'Eternal Masters' },
  { code: 'EMN', name: 'Eldritch Moon' },
  { code: 'V16', name: 'From the Vault: Lore' },
  { code: 'CN2', name: 'Conspiracy: Take the Crown' },
  { code: 'DDR', name: 'Duel Decks: Nissa vs. Ob Nixilis' },
  { code: 'KLD', name: 'Kaladesh' },
  { code: 'MPS', name: 'Masterpiece Series: Kaladesh Inventions' },
  { code: 'C16', name: 'Commander 2016' },
  { code: 'PCA', name: 'Planechase Anthology' },
  { code: 'AER', name: 'Aether Revolt' },
  { code: 'MM3', name: 'Modern Masters 2017 Edition' },
  { code: 'DDS', name: 'Duel Decks: Mind vs. Might' },
  { code: 'AKH', name: 'Amonkhet' },
  { code: 'MPS_AKH', name: 'Masterpiece Series: Amonkhet Invocations' }
];
